### ISSUE TITLE
New MSP command to detect firmware version

### ISSUE THREAD

**Issue by eziosoft** [cleanflight/cleanflight#103]
Could you add new MSP command which returns ie a string with name of the firmware ("cleanflight") and the integer with the version?
It will help me (I'm the author of EZ-GUI) and others to adjust features set in the gui.
The same should be done in BaseFlight, MultiWii etc

The problem:
Right now the AUX settings are not supported in EZ-GUI. Using it can cause problems. I want to block the AUX completely for CleanFlight but I don't have a possibly to detect it. 

Thanks
Bart

**Comment by hydra** [comment]
Ok, i broke up the MSP_API_VERSION command into 5 commands.

```
#define MSP_API_VERSION                 1    //out message
#define MSP_FC_VARIANT                  2    //out message
#define MSP_FC_VERSION                  3    //out message
#define MSP_BOARD_INFO                  4    //out message
#define MSP_BUILD_INFO                  5    //out message
```

See commit 98343af7a2f4d60d7b06207fda54c84d4eb55397

Tested and working with my updated configurator.  Next version of configurator will use them.

I went for a 4 character ASCII string for the variant rather than a number, I just feel it's more flexible this way and less prone to collisions.

Can someone get baseflight and multiwii updated to use at least the API version and FC_VARIANT commands? @treymarc @stronnag ?

**Comment by hydra** [comment]
Done from the cleanflight code perspective.
