### ISSUE TITLE
Derivative Kick from RC input

### ISSUE THREAD

**Issue by borisbstyle** [cleanflight/cleanflight#1110]
I opened this issue to continue discussing theories about preventing the "Derivative Kick" on RcCommand handling from some other PR's.

This is what we are talking about. Slower sampling of Rcdata is causing "infinity" in derivative. This is even filtered data, which smooths it out a bit already!
![rccommand](https://cloud.githubusercontent.com/assets/10757508/8614616/91c3e51c-26eb-11e5-9fe4-b67cd425eb9f.jpg)

This is currently not an issue, rather than a cosmetical thing in my opinion. There are no negative effects in flight, but it would be neater to find a solution where we can smooth it out a bit even if it is preventing ramping a bit to prevent huge rises in D. We don't want to add too much delay preferably

There are some challenges in this one. Sampling of rcdata is pretty slow and is not done during each loop. The solution requires smarter sampling approach as the cycletimes are not constant. Too long sampling will cause much delay and too short sampling will still show ramping.

Also a question we should ask ourselves is. Do we want to solve this? After all it doesn't affect the flight performance and is pretty much filtered down the road (motor/esc).

Just a random log from PID1:
https://dl.dropboxusercontent.com/u/31537757/cleanflight/blackbox_many_flights.TXT

**Comment by borisbstyle** [comment]
@ledvinap 
Let's continue here.

I try different filter approaches in octave from my real data.

**Comment by ledvinap** [comment]
Can you please link corresponding .LOG file?

**Comment by borisbstyle** [comment]
it's added. It's a random log I have. It is visible in any existing log where quick sharp stick movements occure like flips and rolls
https://dl.dropboxusercontent.com/u/31537757/cleanflight/blackbox_many_flights.TXT

**Comment by ledvinap** [comment]
Here is graph with only gyro signal filtered:
![image](https://cloud.githubusercontent.com/assets/2318015/8621011/870b14b4-2723-11e5-990f-6a9fc7af9a75.png)

Not only D-term but also P term is strongly affected by RC setpoint. I'll definitely try RC filter on RC input to PID, with trying few different cutoffs. 20Hz may be good candidate for 20Hz update rate - last trace

**Comment by borisbstyle** [comment]
I made a few graphs as well today and pretty much any filter is better than now :dancer: 

I will start with 25HZ and see how it goes. Thanks for thinking.

**Comment by borisbstyle** [comment]
This is what I will test later today. Just a quick implementation for poll, pitch and yaw.
https://github.com/borisbstyle/cleanflight/commit/82ef24a5b67ba04b076a45841f4bfa20ef1d0269

**Comment by borisbstyle** [comment]
Ok just modified and tested. Works like a charm! Don't notice a difference on the stick and the graph is smooth!
Off to more testing.

**Comment by borisbstyle** [comment]
Some screens of testing. Derivative is still sensitive on the edges.

no smoothing
![no rcsmoothing](https://cloud.githubusercontent.com/assets/10757508/8630202/3af21d8a-2763-11e5-9ec4-2eb213bd25ad.jpg)

22hz
![22hz rcsmoothing](https://cloud.githubusercontent.com/assets/10757508/8630209/408d7bf4-2763-11e5-8caa-3411602746cd.jpg)

15hz
![15hz rcsmoothing](https://cloud.githubusercontent.com/assets/10757508/8630215/484f65c8-2763-11e5-8c43-e10e03fa33a6.jpg)

**Comment by borisbstyle** [comment]
I guess for more effect I need to go even lower.

**Comment by ledvinap** [comment]
Maybe 10Hz, but filtering delay starts to get non-negligible (research would be necessary, quick googling:  in FPS games < 100ms is great, 200ms ok, 300ms almost unplayable).

What about testing FIR (averaging) filter?

**Comment by borisbstyle** [comment]
Yeah sure can you provide some working FIR averaging code and I will try it
out.

I still have to do some more testing with delays. It was too dark yesterday
to do some fpv flying. Thats where you also have some additional delay from
the video equipment as well.
Op 11 jul. 2015 08:30 schreef "Petr Ledvina" <notifications@github.com>:

**Comment by ledvinap** [comment]
Delay on RC channel is in 'human' loop - perception delay/reaction time is added to it. Human brain is extremely good at compensating this delay. My wild guess is that anything under 50ms has negligible effect (but I am quite sure there are purists that can tell 1ms difference .. and connect their TX with Monster ethernet cables ...)

**Comment by borisbstyle** [comment]
yes....it all comes down to what you are used to.
I work in telecom industry and I have made some satellite solutions in the
past for voice and data.

You even can adapt having voice conversations up to 1sec delay once you get
used to it.

But there are guys out there who chose to fly with serialrx as they say the
feel the difference.
Op 11 jul. 2015 10:10 schreef "Petr Ledvina" <notifications@github.com>:

**Comment by ledvinap** [comment]
Maybe it would be worth implementing blind-testing into firmware - choose tested parameter randomly, make notes during flights and compare it to blackbox log afterward .. placebo effect works great ...

**Comment by joshuabardwell** [comment]
>But there are guys out there who chose to fly with serialrx as they say the
feel the difference.

If serialRX has a higher update frequency, then rcCommand should have more discrete steps, therefore derivative kick should be reduced. Maybe that's what they're feeling.

**Comment by Zestforlife808** [comment]
I did some relatively competitive FPS gaming prior to turning to Mini Quads.  I can tell you there is most definitely a perceptible difference between even 50 ms and 10 ms.  There is an ever evolving line of gaming monitors and input peripherals aimed at reducing latency because of this.  If you were to play any modern FPS game with a mouse with 20 ms of input lag, you would have a bad time.  Similarly, it's common knowledge that a person playing with 10 ping has an enormous advantage against someone with 100 ping.  

I don't know how this translates to Quads where inputs are processed and limited by the hardware capabilities of the quad itself.. but I fully agree with those who claim for example that they feel the difference between sbus and ppm.

**Comment by borisbstyle** [comment]
@joshuabardwell 
Faster update will hae more steps and more kicks ;)

@Zestforlife808 
The rc filter only adds 1-3ms delay. That is not really noticaeble at all.
But I even felt the difference between effio FPV cam and sony 600tvl. The difference is like 50ms and huge difference in flight.

**Comment by borisbstyle** [comment]
12hz seemed fine
![12hz rcsmoothing](https://cloud.githubusercontent.com/assets/10757508/8635628/7122036a-282c-11e5-9b75-65d7e821a6e2.jpg)

@ledvinap 
I tried your suggested mod applied to rcData, but that gave me huge delay. Not sure what went wrong and didn't have much time to debug

**Comment by ledvinap** [comment]
@borisbstyle : 

The code using rcCommand is OK. Using rcData would be more complicated.

Did you try to disable D-term averaging? 

Is there some difference in energy consumption?

**Comment by borisbstyle** [comment]
@ledvinap Not yet. There was too much rain and I didn't get to test it all properly. My test list got long lately. I will stop changing other things to complete my test list.
My initial impression is that it didn't make much difference, but needs more serious testing. I will measure motor temperature.....do onboard 120fps recordings and also analyze sound of the motors from the recordings together with logs once I get to it.
My energy consuption was much better yesterday anyway, but I also lowered the gyro_cut_hz and was also using luxfloat.....so it's no real comparisent yet.

I will also test level mode where the stick input is much larger. That's where I expect bigger differences.

**Comment by olelille** [comment]
Isn't filtering the RC input related to reducing the PID factors: 
https://en.wikipedia.org/wiki/Step_response

What about using dynamic PID gain profile based on RC input ?

**Comment by Qopter** [comment]
Hi Boris,

maybe I can help you. I already have a solution to minimize the derivative kicks. The best solution is to interpolate the steps of rccommand. This can be easily done by dividing the large step by (repetition cycle of rcdata / looptime) and add this small step each looptime cycle.

Here my code snippet running at start:

	if (mcfg.looptime > 1200) {
		maxfactor = (40000 / mcfg.looptime + 1) / 2;
	}
	
Here my code snippet running in mw.c each looptime cycle:

	static int8_t factor;
	static int16_t lastcommand[2] = { 0, 0 };
	static int16_t deltaRC[2] = { 0, 0 };
	int16_t setpoint[2];
	
	if (isRXdataNew) {
		deltaRC[ROLL] = rcCommand[ROLL] - lastcommand[ROLL];
		deltaRC[PITCH] = rcCommand[PITCH] - lastcommand[PITCH];
		lastcommand[ROLL] = rcCommand[ROLL];
		lastcommand[PITCH] = rcCommand[PITCH];
		isRXdataNew = false;
		factor = maxfactor - 1;
	} else {
		factor--;
	}
	// interpolate steps of rcdata
	if (factor > 0) {
		setpoint[ROLL] = lastcommand[ROLL] - deltaRC[ROLL] * factor/maxfactor;
		setpoint[PITCH] = lastcommand[PITCH] - deltaRC[PITCH] * factor/maxfactor;
	} else {
		setpoint[ROLL] = rcCommand[ROLL];
		setpoint[PITCH] = rcCommand[PITCH];
		factor = 0;
	}

Unfortunately I don’t use cleanflight. I use my own software based on baseflight. So you have to modify my code that it fits to cleanflight. But I think it’s not a real problem for you. 

This interpolation is similar to a FIR filter. It adds a delay of half a cycletime (10ms for PPM). You can compensate this additional delay by reducing the moving average on rcdata (4 -> 3).

Hope this helps.

**Comment by borisbstyle** [comment]
@Qopter 
Thanks I will definately try it once I prove that the derivative kick has negative influence.
That should fit in the code. I don't see declaration of "isRXdataNew", but I get the picture.

**Comment by ledvinap** [comment]
@borisbstyle : Here is FIR implementation, but not yet finished/tested:
https://github.com/ledvinap/cleanflight/commit/cf5b4cdf59acf25f2268d6d7347633eb9bf0ab6d

Longer filter in filterRCconfig would be probably necessary  and initialization should be added ...

**Comment by Qopter** [comment]
@borisbstyle
"isRXdataNew" is a boolean which ist set true every time rcdata is updated.

**Comment by borisbstyle** [comment]
@Qopter 
I just tried your approach on my bench and it totally smooths out the rcData.

May I ask how I should interprate this maxfactor? And why are you limiting it to 1200 looptime?
           maxfactor = (40000 / mcfg.looptime + 1) / 2;

**Comment by borisbstyle** [comment]
Here quick flight on my basher LOS quad outside. 
https://dl.dropboxusercontent.com/u/31537757/cleanflight/RC_smooth.TXT

@ledvinap 
Can you have a look in my local if thi could be a good candidate for removing averaging. I am now filtering rcData and this should also prevent problematic behaviour on bad RX frames etc.
https://github.com/borisbstyle/cleanflight/commit/74f5854f257f8485947119e0fa0ac5cfb886dcd8

**Comment by Qopter** [comment]
@borisbstyle
maxfactor is the number of intermediate steps. The formula is a simple rounding for integer. I limited it to 1200 looptime because my naze32 can not run faster. By now there are faster FCs on the market so you should limit it to a lower value. But you have to prevent for too low values. Set the default to a medium number, for example maxfactor = 16.

**Comment by borisbstyle** [comment]
@Qopter 
Yes I figured that out. You can run faster when disabling accelerometer. My naze can go down to 300.
I protected that part in case looptime is set to 0. It uses cycleTime to get some maxnumber.
It works really well. Thanks for helping out.

**Comment by ledvinap** [comment]
@borisbstyle : maxfactor is number of loop periods to to transition from old to new RC value (+-1). I don't know why its rounded to even value ...
with 40000 this is 20ms, standard 50Hz PPM frame time.
This works great if actual frame time is greater or equal to expected value. With shorted frame time, there will be residual step when new data arrives.

Personally I would prefer FIR approach - its mathematically simpler/cleaner and easier to encapsulate/hide implementation details. But there is overhead, all filter taps need multiplication, my very rough estimate is 2% CPU time for 20 tap at 1kHz (* 3 RC channels) ... Good for testing, but production code may need some optimization ...

**Comment by borisbstyle** [comment]
I saw your code, but this approach seems more efficient and the graphs look very smooth a you see in blackbox data.

Perhaps the amount of factoring would need to be more dynamic? Maybe some timing built in.
Also there should be statement for maxfactor selecting between serial and analog to assign correct factoring for least delay.

**Comment by ledvinap** [comment]
@borisbstyle : It may be enough to use last interpolated value when computing delta - that way ramp will go from last position to newly received value, avoiding discontinuity if smoothing time is too large.
Then simply hardcode reasonable smoothing value for each receiver type, it won't hurt if the value is not spot on.

**Comment by ledvinap** [comment]
@Qopter: Is there any reason for / 2 in  maxfactor calculation ?

**Comment by ctzsnooze** [comment]
The ideal filter for these kick type spikes is a linear moving average, not exponential moving average, and that's exactly the result here with qopter's code.  

Even if the moving average is not the whole PPM width, but just say half i.e. 10ms, the size of the spikes will still be markedly reduced probably to insignificance, and there will be a bit less delay.   

Perhaps the code could set the duration of the average to see if it is PPM or SBUS input and choose a timeframe to suit?  Or if the user can set it, ideally in ms, they might use 10-15 for ppm 3-6 for sbus, code might adapt that setting for loop time....

**Comment by Qopter** [comment]
@ledvinap
The reason for / 2 in maxfactor calculation is rounding. You can use <pre><code>maxfactor = 20000 / mcfg.looptime;</code></pre> without rounding. I got better results with rounding therefore I implemented it.

**Comment by borisbstyle** [comment]
yes I will check for different receiver types. I actually believe there is only 10hz from softserial and 50hz from ppm. Just do this check:
          if (isRxDataDriven) 
                  10hz
           else 50hz

I will also rethink how to better apply timing for those cases when looptime isn't stable. I think the best idea is to average a few looptimes all the time to have the most accurate timing. I think when we average 5 loops and use that for maxfactor would be most suitable and covers any scenario.
That would also prevent smoothing time being too large as well.

Also some extra conditional protection for PWM/PPM
If there is a failsafe kill switch or disarm on PWM/PPM something more would need to be done perhaps like filtering those 2 additional channels as well. 

Another thing I would also consider is integrating it into annexCode and rework the logic there to prevent repeating calculations for rcCommand to make the code more efficient. A lot of things are happening in annexCode what don't need to run each cycle.

**Comment by ledvinap** [comment]
@Qopter: Thanks, i overlooked that ...

**Comment by ledvinap** [comment]
@borisbstyle : sbus is 11ms between frames ans is data driven ...

**Comment by borisbstyle** [comment]
@ledvinap 
Thanks.

**Comment by borisbstyle** [comment]
@ledvinap Where in the code can you find that SBUS is being refreshed more frequently than other data driven channels? I see just 2 definitions in rx.c

**Comment by ledvinap** [comment]
rxDataReceived is set on each serial frame.

**Comment by Qopter** [comment]
I would suggest to count the loop cycles during a RX frame. This gives you the number of intermediate steps (maxfactor). The problem could be, that the last frame will be measured and that number will be applied to the next frame. If there is a jitter it could be worse than with hard coded RX frame length. Otherwise if the jitter is less than 10% you can cut down maxfactor by 10% without getting great drawbacks.

**Comment by borisbstyle** [comment]
To prevent jitter effect I will remove the multiplier by 2 for rounding. That will truncate some jitter. It is already average from 5 loops now constantly updated. I can also indeed add a little 10% tolerance.

**Comment by ledvinap** [comment]
IMO there is no need for maxfactor to be precise. Just change code so that ramp is generated from last position:
```
if(factor > 0)  factor --;
for(axis) {
  if (isRXdataNew) {
    deltaRC[axis] = rcCommand[axis] -  (lastcommand[axis] - deltaRC[axis] * factor / maxfactor);
    lastcommand[axis] = rcCommand[axis];
    factor = maxfactor - 1;
  }
  // interpolate steps of rcdata
  setpoint[axis] = lastcommand[axis] - deltaRC[axis] * factor/maxfactor;
}
isRXdataNew = false;

```

If maxfactor is larger than rcData period, setpoint will smoothly change slope so that it follows new target (new rcCommand). Only penalty is small delay.
If maxfactor is smaller, then interpolation will be qual to `lastcommand` until new data arrive. Derivative will fall to zero in this interval, it will cause step in D-term, I'am not sure how important it will be ... but it should be quite easy to make sure that maxfactor is large enough ...

**Comment by borisbstyle** [comment]
What do you suggest as a maxfactor choice for any looptime configuration?

One time 5 looptime average? on that way you will always get approximatelly good value unregarding of what configuration is used. 
If I give it a tolerance of let's say 30% you make sure that it's not changed just like that?

**Comment by ledvinap** [comment]
I would still calculate maxfactor from (configured) looptime, using selected RC input to select appropriate delay and add some reserve (30%?). For SBUS (9ms frame update on frSky) that would be about 10-12ms (and rounding up when calculation maxfactor). Some googling should supply values for other supported receivers.

But now it is probably best to use CLI parameter for maxfactor, so that this whole idea can be tested.

**Comment by borisbstyle** [comment]
Well my goal is to get the least delay possible for all, but I will add both for testing. When cli maxfactor disabled dynamic setting derived from cycletime or looptime and otherwise it will use the cli setting.

**Comment by hydra** [comment]
Would suggest thinking of a slightly better name than maxFactor.  Its a bit vague.  Looking forward to reading about your testing results and comparisons too.

**Comment by ledvinap** [comment]
rcRampPoints?

**Comment by borisbstyle** [comment]
I already formalized some of them in my code over here. 
rcInterpolationFactor ???

**Comment by borisbstyle** [comment]
Draft code
https://github.com/borisbstyle/cleanflight/commit/e77beb6feb6bb2dbe73953997d33a8bce7ab0094

**Comment by Zestforlife808** [comment]
@borisbstyle 

I downloaded the naze hex from your dropbox yesterday and didn't notice any shark fins on the dterm while using luxfloat.  Is smoothing enabled on that version?

**Comment by borisbstyle** [comment]
Ok did some cleanups in the code and retested.
@ledvinap I also tried your suggested approach, but that somehow didn't end well.

Final trace from my mini h after a lot of testing with my small mini x.
https://dl.dropboxusercontent.com/u/31537757/cleanflight/luxfloat_minih.TXT

I also found out that this works extremally well with these filters. Incredibly locked in
gyro_lpf = 0
gyro_cut_hz = 60
pterm_cut_hz = 40
dterm_cut_hz = 15

**Comment by borisbstyle** [comment]
By the way I am getting impression that this definately improves tuning and flying characteristics. I now also think that derivative kick wasn't usefull at all as we first thought. Derivative kick was actually lowering response as it was working in the opposite direction than P

**Comment by ctzsnooze** [comment]
Boris, filtering RC does not remove derivative kick. I have tried to explain this in the past, I try again.

Let's look just at pterm trace.  It is error based and has no dterm kick, but it has sawtooth, because the quad responds within the PPM period and the error is reduced as the quad turns.  If we smooth RC so the input PPM change is not a step, but a straight line, we we lose the abrupt change in error, so no more sawtooth on pterm and the gyro follows smoothly.

So the RC filter removes saw-toothing in quick-responding quads.

In Dterm when targeting error we also get saw-tooth, but here it is due to the sudden change in derivative and is due to kick.  Now let's say that for some filtering reason, maybe smoothing in RC, we have a kick 100 units high spread over 4 cycles.  The area under that curve represents an overall change in Dterm.  Now if we smooth it to be 50 units high over 8 cycles, we same have the same 'effective' change in Dterm.  The effect of the derivative kick on Dterm over time does not change.  If we make it 1 unit high over 400 cycles, the effect is the same.  

If we smooth RC so that the derivative kicks are no longer visible, the 'energy' in the derivative kick remains.  It is just 'invisible' now.  It has the same effect on Dterm as before, but it is just not visible anymore.  

You will notice that if you go back to original lux dterm behaviour (not target error) but retain RC filtering, the dterm curves will be different from the new error targeting method, proving that the effect of the kick remains.

Another way of thinking about this is that derivative kick is due to the setpoint change.  At some rate, when the derivative is determined by error, every time you change setpoint, whether the change is fast or slow, there is a change in derivative (either abrupt or gradual) and that change ends up in dterm.  

Let's be clear for once and for all, smoothing RC does not remove the beneficial effect of derivative kick.  It only smooths it out, like it smooths out the sawtooth in pterm.

**Comment by ctzsnooze** [comment]
PS that mini-H trace is pretty amazing, isn't it!  How good is that!  :-)

The gyro trace looks almost precisely the same as the stick trace - like the quad is EXACTLY following the stick input.  And there is no yaw pterm sawtooth in the motors anymore, in fact no sawtooth in the motors anywhere.  

Its kind of curious that there is wobble in pterm and motors on sharp inputs, but the gyro trace is so perfect and does not show those wobbles.  I can't really explain why the motors must wobble to make the gyro trace so rock solid.  Anyhow the gyro trace is the proof of the outcome I guess and it is - perfect!

Did the motors sound different?  I think that sometimes on hard inputs they used to make a kind of harmonic overtone noise  that I rather liked... maybe now they just sound boring???  ha ha  :-)

PS - A person on RCgroups asked if the gyro recordings in BlackBox are affected by the sw filters, I think they are only affected by gyro_lpf?

**Comment by Zestforlife808** [comment]
I tried the latest hex if anyone wants to see my results.  This is just some light flying LOS with a 2 pack tune.  Haven't had a chance to do any flips or rolls.  There's some slight bounce on sharp roll inputs but I don't want to damp the stick feel excessively.      

https://www.dropbox.com/s/8mwq1es34oiwmu9/LOG00239.fixed.TXT?dl=0

2015-07-13 @ 16:38:40 -- Running firmware released on: Jul 13 2015 21:49:19

cobra 2300kv 
5x45 
KISS
blackout mini h

gyro_lpf = 0
gyro_cut_hz = 60
pterm_cut_hz = 40
dterm_cut_hz 15

luxfloat 2
looptime 600
roll 1.0 .030 22
Pitch 2.3 .040 30
yaw 3.6 .060 15

**Comment by borisbstyle** [comment]
@ctzsnooze
Well lets say it doesn't remove the energy, but it wastes more enegy over the same period. The motors are going to try to deaccelerate and accelerate, but the energy during the kick will only be wasted as motors will never be able to keep up with that.
At the end the total consumed energy for the same move will be more.

The short mini h flight was actually a LOS flight outside in the dark. The roll is completaly mistimed as I was flying on LEDs.
Still need to do a final tune, but it feels nice and responsive and it is easy to keep the quad on same spot.
The yaw was the most dirty axis and rc smoothing seemed to help it together with lowered vut frequencies the motor sound is pretty much like on the bench.

The roll/flip sound also got more silent. The violent sound of hard flips and rolls is more gentle and quite.

Another thing:
PID1 always seem to have weird level mode. I never could get a grip in it. The problem was basically that it could be tuned to be super snappy and stable, but as soon as you would make sharp stick moves it would oscillate.
The level mode uses bigger stick movementd and that causes more ramping in normal operation. That is fixed now as well.

**Comment by borisbstyle** [comment]
@Zestforlife808
If it slightly bounces on roll you would need more D I would say.
Can you also try the latest hex so we can compare?

**Comment by borisbstyle** [comment]
@ctzsnooze
gyro traces in blackbox are affected by both. gyro_lpf and gyro_cut_hz

**Comment by Zestforlife808** [comment]
@borisbstyle 

I think I have the latest.  I downloaded it maybe 5 hours ago.  Also did something change with blackbox?  My logs won't play unless I copy a header from a log from a previous version.  

This is what my naze version says.

# Cleanflight/NAZE 1.10.0 Jul 13 2015 / 21:49:19 (a41c14a)

**Comment by borisbstyle** [comment]
that version is from few days ago but should be fine.

Are you using the latest blackbox viewer?
I know the header has been changed in the last master but it works on my
viewer.
Op 15 jul. 2015 08:47 schreef "Zestforlife808" <notifications@github.com>:

**Comment by Qopter** [comment]
May I put in my two cents. The derivative kick should have the same effect with or without rcsmoothing. But that’s only right on a linear system. Our system is not linear or in worst case the spikes are limited. Then information get lost. Furthermore I don’t know what does the ESC with this fast transients. And as Boris mentioned these up and downs are wasting energy even more they produce vibrations. I would say the probability is high that rcsmoothing is not only cosmetic but also a significant improvement.

**Comment by Qopter** [comment]
@borisbstyle
I made a modification in level mode a long time ago. Can’t remember why. Maybe it’s the solution for you. Give it a try.

            } else { // it's the ANGLE mode - control is angle based, so control loop is needed
                AngleRateTmp = (errorAngle * cfg.P8[PIDLEVEL]) >> 5;
                AngleRateTmp = constrain(AngleRateTmp, -1500, +1500);	// 1500 limits to 400deg/s
                AngleRateTmp -= (gyroData[axis] * cfg.D8[PIDLEVEL]) >> 8;
            }

**Comment by ctzsnooze** [comment]
Don't get me wrong, I'm very happy to see the kick induced spikes gone, however the overall kick effect was good.  A median filter would have got rid of the spikes and we would have had a smooth dterm trace - but that would not have been good. 

Theoretically I fully expected that with RC smoothing that the dterm trace would smooth out but the 'effect' of the kick on dterm would remain.  The other benefit of RCsmoothing was to remove pterm spikes, and they were also quite big.

Qopter your point about the nonlinearity is very good, it could be that with RCsmoothing there may be an even greater kick effect overall due to better integration of the whole of the kick effect, hadn't thought about that possibility.

And Boris your point that the kick effect may now be more effectively translated to the motors is good also.  

So yes we may find and even more favourable Dterm response to quick stick inputs now.

Additionally, those PIDsum sawtooths and spikes would have resulted in Z-axis jitter. BLHeli adds random jitter each ESC which would translate some of that Zaxis jitter into the other axes.  None of that would have been good, just adding to frame noise.  

Thanks Boris for your feedback on the sound of the motors.  I'm sure in quick yaws they are much nicer.  That yaw Pterm sawtooth effect was very obviously going into the motors on lots of traces.

I have flown a lot in horizon and less in level, but have used them both in Lux and they both performed OK.  I didn't try hard or look hard at them.  What problems have people been experiencing?

**Comment by borisbstyle** [comment]
@Qopter I am not the guy to determine weather level mode is good or not, cause I don't really use it. I suggest making a PR if you think it gives improvement? Get rid of baseflight and put cleanflight on so you can contribute more :D. Thanks for this filter suggestion. 

By the way what other speeds I can expect from serial protocols? I now only have SBUS as different
           switch (masterConfig.rxConfig.serialrx_provider) {
    	        case SERIALRX_SBUS:
    	            rxRefreshRate = 11000;
    	            break;
    	        default:
  	            rxRefreshRate = 10000;
    	            break;
            }

**Comment by Qopter** [comment]
@borisbstyle
My pleasure to help you!

It’s not so easy for me to switch over to cleanflight because of the many modification I made in baseflight. I had the thought as blackbox came out. But then it was easier to implement BB in my modified baseflight than vice versa. So I stay with baseflight.

**Comment by borisbstyle** [comment]
pr has been merged
