### ISSUE TITLE
Three beep beep beep sound after power mean?

### ISSUE THREAD

**Issue by yuan0226** [cleanflight/cleanflight#1118]
Hi,I would like to know a beep beep beep sound after power is what it meant, thank you!

**Comment by thenickdude** [comment]
Three beeps means that the gyroscope calibration has completed successfully. It's important that the quadcopter stay still on the ground until these beeps sound so that the gyroscope calibration isn't thrown off (if you move it substantially during calibration, then it'll automatically start calibration again and the three beeps will be delayed).

**Comment by yuan0226** [comment]
Thank you for your reply, I understand.

**Comment by hydra** [comment]
A documentatiob update with this info would be useful

**Comment by joshuabardwell** [comment]
Done.

https://github.com/joshuabardwell/cleanflight/pull/1

**Comment by hydra** [comment]
The PR is against the wrong fork, I will merge anyway.

**Comment by joshuabardwell** [comment]
Sorry. I'm still figuring out Git. I thought I was supposed to make a new fork for my changes, vs. branching the master. Is that not right?
