### ISSUE TITLE
Blackbox - write to ring buffer sort of log

### ISSUE THREAD

**Issue by bexamous** [cleanflight/cleanflight#1265]
It'd be nice to be able to leave logging enabled, so you always had the last X minutes of flight data and log would just loop around and write over itself..  from a usablity standpoint I think this is much preferable than having to manually wipe it all the time.

And from debugging perspective it woudl be more handy for any issue that was intermitent.  Eg in BorisB's beta thread on rcgroups, few people see these little twitches every once-in-awhile... but for me I happens every few packs.

Actually getting that on log would be a huge PITA using internal storage.  But it'd be nice to see it happen and then just go land and have last 2 minutes of data.

Only issues would be I'm not sure if doing an erase in loop is too slow, or how many erases internal storage is rated for.

**Comment by thenickdude** [comment]
Not possible because the dataflash erase time is too slow. e.g. m25p16's sector erase timing is 800ms typical, 3 seconds maximum. This would require us to be able to buffer at least 800ms (and probably around a second) of log data while the erase takes place. That equates to about 24kB, and we don't have that much RAM available for buffering.
