### ISSUE TITLE
MSP_RX Issue

### ISSUE THREAD

**Issue by khockuba** [cleanflight/cleanflight#1333]
When using MSP_RX as reciever in Cleanflight the reported values are completly gibberish and some of them stucked on 855, quad is basicaly non controllable, on 1.9.0 it was perfectly fine.

**Comment by hydra** [comment]
Oh wow!  Someone is using MSR_RX! :smile:  @ProDrone This probably needs your attention.

**Comment by ProDrone** [comment]
Oh, well, what is it used for? I see in http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol
a reference to "UART radio projects", which seems to be here: http://www.multiwii.com/forum/viewtopic.php?f=8&t=3101&start=100 and appears to be an abandoned project...

Maybe we keep it for backward compatibility then? Correct me if i'm wrong but my solution would be to remove it from the code.

**Comment by conkerkh** [comment]
I've programmed my own UART reciever based on esp8266. Apart from the fact I'm using it, I would say that this solution is really coninient since you can also get telemetry out of this thus leaving all other input pins for something else. If you don't wanna keep it please point me to the code that is used there. I'll compile my own firmware

**Comment by atomiclama** [comment]
@conkerkh that is exactly what I'm in the middle of developing. Correct me if I'm wrong but can't you just use the MSP command to set the RCcommand or have I missed something there.

Do you have any details / web links to what you are doing. See if I have missed something, get some ideas. Cheers

**Comment by conkerkh** [comment]
Well yes but still it has to be selected in configuration tab in clean flight at least that's what I found to be working. Actually only sending stuff is fairly easy job. My work to be honest is based on loads of other infos found on the Internet. I can send you simple C function used to update rc values. I might release the code on GitHub but it needs more work because it's Woking efficiently however it's pretty horrible to look at and work on:P

**Comment by atomiclama** [comment]
Thanks but I have plenty of code to use ;-)
Most from internet some of my own.
I'll check this over if no one else fixes it, once I get to this stage. 
Cheers

**Comment by conkerkh** [comment]
Well on 1.9 it was ok so you can just roll back till someone fixes this

**Comment by ProDrone** [comment]
I see there is still interest in this feature, so i will look into this problem. Is there a simple app that provides stick and switch input using msp commands?

**Comment by atomiclama** [comment]
Not that I have found yet, sorry

**Comment by conkerkh** [comment]
Unfortunately no at the moment I was trying to do this however I found it a bit unreliable due to lack of feedback what you are actually pressing. Impossible to fly this way. Maybe only for switching modes

**Comment by hydra** [comment]
Fix merged.
