### ISSUE TITLE
1.11 RC no longer provides FrSky telemetry on Rev6 through Softserial

### ISSUE THREAD

**Issue by mknippen** [cleanflight/cleanflight#1534]
To reproduce:
1. Use official build, or build 2335 with: FrSky Telemetry, Softserial. Have Smartport green wire go to pin6
2. Dump settings (mine are provided below)
3. Move to RC1 with full chip erase
4. Restore dumped settings

Also, when trying to set telemetry_inversion = 1, it now fails. This could very possibly be the root of the problem.

CLI Dump:
[telemetryDump.txt](https://github.com/cleanflight/cleanflight/files/49038/telemetryDump.txt)

Using Cleanflight Configurator 1.1 on a Mac.
Naze 32 Rev6

I tried posting in IRC a few times first, I didn't get any replies. If this is better put somewhere else in the future, please advise and I will do whatever works best.

**Comment by qfather** [comment]
Looks like you pasted an old config back into the CLI.

Read the release notes, which state that "CLI get/set commands have changed. some variables are now set using OFF/ON instead of 0/1."

I can see from your dump that you have

    set telemetry_inversion = 1

Change it to

    set telemetry_inversion = ON

and you should be good to go.

Check your other variables.  Anything that was 0/1 to disable/enable is now OFF/ON.

**Comment by mknippen** [comment]
this fixed the issue. I guess I missed this. Thanks for the help!
