### ISSUE TITLE
Motor referencing

### ISSUE THREAD

**Issue by loeschr** [cleanflight/cleanflight#2158]
The numbering, or more correctly, the motor location sequencing between the config screen diagram and the mmix commands is inconsistent.  The diagram on the config screen orders them rear right, front right, rear left and then front left.  The mmix command orders them front left, front right, rear left, then rear right.  Suggest that the motor location sequencing be made consistent.  If using the mmix ordering, this would allow moving from LibrePilot to CleanFlight more straight forward.  Currently one would have to either change ESC leads or use the mmix command to remap.  Even using the mmix command could lead to errors as it differs in sequence from the config screen mapping.

**Comment by hydra** [comment]
it's not something were's going to change now.  So many PCBs and other documentation have been manufactured and printed using the motor order as it is.

Not sure what you mean by the mmix command orders them from how you say it does since it just prints out the mapping; it does no reordering - users do that.

It likely would be useful to be able to select the motor order easier in the GUI configurator but that is unreleated to the mmix.  Also, see #922.
