### ISSUE TITLE
VFAS NOT READING CORRECT 

### ISSUE THREAD

**Issue by fpvflyby** [cleanflight/cleanflight#2237]
NAZE32 REV 6 NOT SENDING FULL VOLTAGE TO RADIO. ALL OTHER TELEMETRY WORKING CORRECT

**Comment by AmiSMB** [comment]
First thing is not to use all capitals as per netiquette rules otherwise it appears as you are shouting. Check the painless360 video which show you how to calibrate the telemetry in Cleanflight at aroung 6:33 https://www.youtube.com/watch?v=rrnxfn1mCXk. You will need to change the voltage scale value until the value you see in the telemetry is correct.

**Comment by fpvflyby** [comment]
Sorry about the capitals. Must have had caps lock on. Thanks for the advice. But I got it figured out thanks again
