### ISSUE TITLE
spracingf3 - cleanflight motor problem

### ISSUE THREAD

**Issue by marcoberri** [cleanflight/cleanflight#2263]
Hello,

I mounted the new Afro , replaced an engine that no longer worked, recalibrated the esc but the problem remains that two motors are out of calibration when using the remote control .

I attach these three videos .

if you use the engines from the console of cleanflight no problem when I send the signal from the remote control answer incorrectly . Yet I recalibrated all.

this is the test by the engine management cleanflight motors start together regularly

[url]https://www.youtube.com/watch?v=64WKLCVf66E[/url]

this with the remote control :

[url]https://www.youtube.com/watch?v=1UiFYOiBCmE[/url]

only two engines respond immediately .

and that when I use the remote control you can see that the signal provided on the engines is not balanced .

[url]https://www.youtube.com/watch?v=Yc9JWvOnhBo[/url]

I do not understand....

... Give me a hand?

thank you.

**Comment by AmiSMB** [comment]
The issues that you are having suggest that the craft thinks that it may not be level which is why the motors are starting incorrectly. Looking at the numbers for the motors I would say that the min_output to your escs is wrong. I set mine as per the recommendations of Joshua Bardwell in his [video](https://www.youtube.com/watch?v=WFU3VewGbbA). I think that you should set these values correctly and then re calibrate all of your esc's.
