### ISSUE TITLE
Flight - Autoland

### ISSUE THREAD

**Issue by bennyh88** [cleanflight/cleanflight#234]
I see there is already a flight controller failsafe that reduces throttle for gentle descent, then switches motor off after x amount of time. Can this be improved to utilise the baro to prevent it shutting the motors off mid air or leaving them spinning on the ground? Baro could also be used for control of rate of descent. 

While gps support is still in it's infancy this is the best fail safe option.

Having it switchable is handy for openLRSng users as failsafe can be stored on the fly. Would also make a good panic button.

Thanks,

**Comment by heathicus** [comment]
I also think a more flexible failsafe feature could be created.  Currently, there is basically one behavior with a few variables that users can adjust (change to angle mode, set throttle at x for y length of time then disarm).  

I would like the action and the time to be configurable, and the ability to stage multiple actions.  My personal preferred failsafe would be:

Change to Angle/Horizon with Altitude Hold for 10 seconds.  Activate buzzer.  This would hopefully give me time to reorient myself to restore communication.

If communication is not restored after 10 seconds, begin a controlled descent using barometer.  After 30 seconds, disarm.  

If, any time after failsafe is activated, acc/gyro readings start fluctuating well beyond a baseline, the craft probably hit something so kill power and disarm immediately.

**Comment by fiveangle** [comment]
I came here to request "failsafe test" feature, which will allow users to tune failsafe parameters with an aux switch, then once they are tuned, perform final test by physically turning tx off.  As it is now, it is impossible to tune the (relatively crude) autoland feature without possibly destroying the craft.

I also feel the failsafe feature needs improvement.  So many do not implement it because it isn't obvious how to tune it.  Most understand what "PWM" means, but how to set that to safely land the craft, and testing it is so risky, people put it off until they have a catastrophic crash, and then set it up.

Better basic "tools" to setup failsafe should be priority, and I feel the "switch" portion of this issues suggestion is 80% there.

If others feel a new issue should be raised specifically for adding failsafe test aux channel, let me know and I'll do it.

-=dave

**Comment by heathicus** [comment]
I really like the idea, fiveangle.  I think you should create a new feature request for this as it is a related, yet different idea than the feature requested with this issue.

**Comment by hydra** [comment]
There are two things here:
1. autoland support via switch.
2. autoland support via failsafe.

Let's keep this focused on 1.

As I see it, the things that's missing are:
1) descent rate detection and correction
2) detection of when craft has landed.

You can use blackbox logs to investigate what the sensors do when you land or crash your aircraft.

**Comment by ondras** [comment]
@hydra please, what is the status of feature? It is not clear to me why the issue was closed. Can we expect this functionality, or are the some limitations preventing you from implementing it? Just asking for a friend :wink: Thanks for a reply!
