### ISSUE TITLE
Implement 'global variables'

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight#2378]
Some recent feature requests may be solved by using concept of 'global variables' (https://opentx.gitbooks.io/opentx-taranis-manual/content/global_variables.html)

Global variable source: 
- RC channel
- (Servo) mixer output (?) - some of OpenTx mixer features may be implemented, I am missing multiply mode
- RC adjustment (profile or rate profile specific)
- Mode
- Profile
- Telemetry value (?) - user defined voltage throttle compensation

Global variable may be used in:
- led color / index (#2377)
- max_angle_inclination (#2360)
- failsafe values (tunable failsafe parameters)
- servo mixer - It will allow easy in-flight trimming in airplane mode
- motor mixer (?) - motor tilt mechanism / throttle compensation / .. 

Other ad-hoc CLI variables may be probably replaced by GV, simplifying code base

This may be quite powerful tool or weapon to shoot ones foot .. but it is IMO worth the benefits ..

**Comment by hydra** [comment]
Yes, it's key to modulations to find some way of data ownership and data access.  I have been thinking about this kind of stuff quite a lot recently.  I'm thinking we need something like this BEFORE we try and add a menu system, otherwise it'll be a nightmare.

If you, or anyone else, has any other references of projects that do this kind of things then please share details and links.
