### ISSUE TITLE
Passthru of RC channels 

### ISSUE THREAD

**Issue by bennyh88** [cleanflight/cleanflight#246]
On quad setups there are 2 spare RC outputs, would be nice to be able to use them in passthrough mode, for example to control a gimbal. Would make for neater build depending on receiver location etc, not essential but nice to have.

**Comment by Hwurzburg** [comment]
What would be really useful: since you can individually enable softserial ports, it would be nice to have enabling an inidividal port OVERIDE "set gimbal flags=4" for that port (or allow pins 7/8 in passthru when gimbal tilt is enabled)....so that you could have a softserial port for, say, FRSky telemetry,...yet pass thru AUX3 and 4 for running/controlling a loud 12v buzzer (for when you use something like a DR4II that only outputs PPM and no other channels)
