### ISSUE TITLE
GPS - Allow users to set GPS update frequency

### ISSUE THREAD

**Issue by l2smith2** [cleanflight/cleanflight#251]
having control over the GPS update frequency from the gui to find the value that provides better accuracy for the unit you are using would be very helpful. Or any other important values you normally need to passthrough to ucenter.

Being able to set the GPS auto config parameters from the gui gps page so setting it all up is quick and simple without messing with passthrough, ucenter and rebooting over and over.

**Comment by RustyPaint** [comment]
+1 from me as well.  This GPS unit (http://www.hobbyking.com/hobbyking/store/uh_viewItem.asp?idProduct=64142) cannot obtain a lock with such a fast sample rate (5 times a second).  A rate of 2 updates per second is enuf for this unit to work well.

Wanting to use this unit for a MiniQuad, since it is such a small form factor, and want the arrow pointing to home functionality for the OSD as well as ground speed (using a KV Team OSD board).

**Comment by andymac4182** [comment]
I know people that have that GPS working with Cleanflight. @RustyPaint

**Comment by RustyPaint** [comment]
I have it currently working in NMEA mode at 1 hz refresh rate just fine in portable mode.  I managed to manually set it up to use the UBLOX protocol with 2 hz refresh rate in pedestrian mode at one point.  The problem is that this GPS unit will loose its saved settings when the backup battery dies.  Since the backup battery dies in about 8hrs or less, it always resets back to NMEA, 1hz, 9600 baud, portable mode.  It would be nice to have the auto configure work with it, but allow to change the refresh (sampling rate) to overcome the limitations of this GPS unit.

**Comment by l2smith2** [comment]
I've found the settings won't save if changed in center while using pass
through mode.

**Comment by SamuelBrucksch** [comment]
You can easily adjust it yourself. In frsky.c check for method "handleFrSkyTelemetry" there you have 3 timing conditions:
 if ((cycleNum % 4) == 0)      // Sent every 500ms
if ((cycleNum % 8) == 0)       // Sent every 1s

And avove those two it is sent ever 125ms. If you want to have gps data every 500mw just move
#ifdef GPS
        if (sensors(SENSOR_GPS)) {
            sendSpeed();
            sendGpsAltitude();
            sendSatalliteSignalQualityAsTemperature2();
        }
#endif
To the time condition that you want to have.

For 5hz for example the time woulöd be every 200ms, that would be
 if ((cycleNum % 2) == 0) 
Which is actually 250ms (4hz) but still better than 1hz.
