### ISSUE TITLE
Limited MSP update rate

### ISSUE THREAD

**Issue by christianrauch** [cleanflight/cleanflight#2571]
The `MSP_STATUS` message tells me that cleanflight (1.14.2) is running with a looptime of around 1000us/1000Hz. Still, I am only able to read messages at about 90~100Hz (tested with [msp C++ library](https://github.com/christianrauch/msp) and [pyMultiWii](https://github.com/alduxvm/pyMultiWii)).

I am expecting to have a MSP update rate that is close to the loop rate of the controller. E.g. this is true for baseflight (3500us, 233.263 Hz) and 8bit MultiWii (2800us, 340Hz). Since 1.12 the MSP update rate appears to be limited to 100Hz.

**Comment by andre92** [comment]
Correct, since cleanflight 1.12 it is running a task scheduler instead of a super loop construct. All the code has been broken up into small tasks that each run at their own rate. This allows more important things (like gyro update and pid loop) to run more often, while less frequent tasks can be skipped when they do not need to be executed. serial receivers run at about 100hz so checking the serial ports more often is not needed, so you can better spend cpu time elsewhere. Same for compass and barometer updates, which run at 15 and 40hz respectively. This is more efficient than checking everything each loop.

**Comment by martinbudden** [comment]
@christianrauch , why do you want/need a higher MSP update rate?

**Comment by andre92** [comment]
Maybe because of buffer size. Not sure how big the buffer is, but with 100% uart usage at 115200 baud, it would need to hold about 115 bytes at 100hz.

**Comment by christianrauch** [comment]
@martinbudden I intent to implement control algorithms that run on a companion computer.
@andre92 The problem with the MSP update rate is, that it is shared amongst all incoming and outgoing messages. E.g if I request `MSP_RAW_IMU`, `MSP_MOTOR` and `MSP_ALTITUDE` at the same time, the effective update rate per message is reduced to 33Hz which is quite low for a IMU. It is further reduced if you set the RC channels via `MSP_SET_RAW_RC`. I see that there is no benefit for serial receivers if their maximum update rate is 100Hz, but this task also limits MSP communication.

I see that the serial task period is hard coded in `fc_tasks.c` to 100Hz. Is there a way to change this value via the GUI or CLI?

**Comment by andre92** [comment]
No, it is hard coded. It requires a custom build to change it. iNav is working on variable task rates for IMU and acclerometer frequencies. You could do something similar with Serial.

**Comment by martinbudden** [comment]
@christianrauch , yours sounds like a legitimate use case.

Unfortunately, as @andre92 points out, it is hard-coded and can't be changed via CLI or GUI. Doing a custom build is quite easy though.

Since this does sound useful, I'll do a betaflight PR to allow setting the serial task period via the CLI. With a bit of luck it should be in time for the upcoming 3.1 betaflight release.

**Comment by martinbudden** [comment]
@christianrauch , I've changed this in betaflight, see https://github.com/betaflight/betaflight/pull/2060

This should be available in betaflight 3.1 release candidate 6 - see https://github.com/betaflight/betaflight/releases (currently we are on RC5)

**Comment by christianrauch** [comment]
@martinbudden thank you very much for this feature! With betaflight I can also easily increase the MSP baudrate allowing me to use much higher MSP update rates.

Is there a chance that this feature gets merged back into cleanflight?
