### ISSUE TITLE
no option to Backup and / or Restore

### ISSUE THREAD

**Issue by nathanniice** [cleanflight/cleanflight#2575]
on my cleanflight configurator from Chrome, i do not have the option, as i used to have, on the setup page underneath the reset settings there is nothing.  i am trying to restore to default settings.   please help.

**Comment by stronnag** [comment]
(a) This is a configurator issue and should be entered under the configurator project
(b) backup and restore was removed because it didn't work; see also #2466 
(c) Please check for old issues before wasting developer time with new bogus non-issues
(d) you can use CLI dump for reliable backups

Please close this non-issue.
