### ISSUE TITLE
Select pins for external hardware without having to compile a special binary

### ISSUE THREAD

**Issue by LupinIII** [cleanflight/cleanflight#265]
Most of the pins for external hardware are fixed within the source code. So for every different board changes to the code have to be made and a separate binary has to be created.
In my case I'd like to use SBUS, Smart port and GPS with an update rate higher than 1Hz, all of which needs a hardware USART) with a very small STM32F103C dev board, where I have access to all pins.
Even a STM32F103C has three USARTs, but the pins for the third one are used for I2C2, where the sensors are connected. It would be nice, if there were an easy way to remap I2C to I2C1 (could be PB6/7 or PB 8/9) and free up PB10/11 for the hardware USART and then have the ability to assign a "serial_port_x_scenario" to it. And I wouldn't mind still having a softserial for CLI ;)
In a similar fashion it would be very useful if the PWM channels, beeper, LED, sonar, VBAT aso. could be switched to different pins, if needed (within the capabilities of the MCU of course; no use in setting VBAT to a pin that has no ADC).
Since a goal of cleanflight is to run on alot of different hardware, this should make thinks easier in the long run.

**Comment by hydra** [comment]
@LupinIII It's not as simple as just pins.  The pins use hardware functions and some hardware functions clash (timers, irqs, dma channels, etc).

Going to close this since it's too vague to do anything about.  #357 is planned and known.

Since this issue was opened there have also been improvements in the target.h file with regards to defining perhipherals, pins, clocks, etc.
