### ISSUE TITLE
Sensors - Board_align_pitch and board_align_roll values transposed

### ISSUE THREAD

**Issue by MassiveOverkill** [cleanflight/cleanflight#272]
If you set board_align_pitch it modifies board_align_roll value and vice-versa.  The model animation icon display is correct however.  I also have board_align_yaw = 270 (or -90) so I don't know if that is affecting the values.

**Comment by MassiveOverkill** [comment]
I can confirm that this is affected only when you have board_align_yaw set set.

**Comment by imagebuff** [comment]
Hit this issue as well today after adding pitch adapters to the motors.  Really need this fix for angle mode to function properly.  This is not safe as angle mode takes off forward instead of hovering.

**Comment by umdpru** [comment]
this bug bit me yesterday when I installed the 10º motor mounts. I have yaw set to 90º to get the usb connector to the side. The code doesn't consider the yaw when it calculates the new offsets for pitch/roll if you want them. It would be virtually impossible to determine the correct offsets if you had yaw at anything other than right angles (90, 180, 270, 0/360). 

The simple solution until this bug is ironed out is to manually swap them - i.e. use roll offset in lieu of pitch offset. That worked fine on my build yesterday.

**Comment by hydra** [comment]
See #8

**Comment by hydra** [comment]
After looking at this and reading the various issues regarding board alignment it appears to be correct.  I even went as far as removing the old board alignment code since it was a copy of the vector rotation matrix code that is used in many other places.

See 4fcecbd6674160bc872690f7fab2b492ada95bb1.

If that code was wrong then the attitude calculation code would not be working either.

It's possible that it's just not clear to users how to setup their aircraft when using board yaw alignment.  In which case this is a documentaton issue and PR's that update the documentation are welcome.  

The comment by https://github.com/cleanflight/cleanflight/issues/272#issuecomment-88901639 above is the answer.

With regards to a comment made by @archon03 here: https://github.com/cleanflight/cleanflight/issues/266#issuecomment-102704076 - I have asked for more details.

At least by opening this issue a code cleaning was performed and the code was looked at.

**Comment by Archon03** [comment]
Posting here because MassiveOverkill, imagebuff, and umdpru all describe the same problem I am seeing.

Board alignment works correctly UNLESS these 3 conditions exist simultaneously:

1) board_align_yaw set to 90 (to make USB accessible on left-side of quad)
2) board_align_pitch set to -10 (due to angled motor mounts)
3) Angle mode is active (problem does NOT affect rate mode)

Example: My Naze32 is mounted with the USB port on the left side of the quad (board_align_yaw 90).  I add angled motor mounts (board_align_pitch -10).  I lift off in Rate mode and hover; the quad flies perfectly with nose up 10 degrees so the motors are level.  While hovering, I flip a switch to activate Angle mode and suddenly the quad leans forward 10 degrees and leans left 10 degrees.  I am able to compensate by pulling the stick back and right.  When I switch back to Rate mode, the quad becomes controllable again, and I am able to hover with only minor stick inputs.

Again, only if these 3 conditions are true does the board_align_pitch appears to be applied to board_align_roll.  I suspect this is because the pitch adjustment is being applied to the actual front of the board which is pointing right in my example, instead of the yaw adjusted virtual front of the board.

Thanks for the great work, hydra.  I hope my description and example helps track down this problem.

Nick

**Comment by umdpru** [comment]
the roll and pitch compensation directions do not rotate with the yaw
alignment change. They maintain their original alignment to the
physical board. When you rotate yaw, you must mentally alter
roll/pitch.

It would be better if the software automagically rotated roll/pitch if
yaw were rotated to make adding pitch offset for angled motor mounts
more intuitive for the first timer.

**Comment by Archon03** [comment]
umdpru, I agree with you, but I believe the swapped roll and pitch is only true in Angle/Horizon mode.  In Rate mode, roll and pitch alignment are applied differently (swapped?).  My experience is that switching in or out of Rate mode with 10 degree angle motor mounts and board alignment of 90 causes roll and pitch alignment to be applied differently making the quad uncontrollable.

**Comment by ledvinap** [comment]
@Archon03 : In rate mode only angle derivative is used, so relatively small offset  caused by assumed wrong rotation order is not that important.

I am just guessing, but rotations are be applied in roll -> pitch -> yaw order (in body axes)
In your case that means that pitch is applied first (board is misaligned in both axes now) and result is rotated 90deg, resulting in 'swapped axes' you describe.
In fact you need to compensate roll first (-10deg, after this board will be horizontal) and than compensate yaw rotation (90deg)
