### ISSUE TITLE
[DOCS, OSD/PDB] - Please provide documentation for bus switch functionality

### ISSUE THREAD

**Issue by biank88** [cleanflight/cleanflight#2737]
## Hardware configuration
- flight controller: **SPF3 deluxe**
- osd & pdb: **SPF3-OSD-PDB**

The two boards are stacked using four pairs of headers as described in the official manual for the **SPF3-OSD/PDB**:
- 5v/GND
- UART1 (T1/R1)
- Vbat+/GND
- Buzzer+/GND

## Problem:
I cannot connect (via the CF-Configurator) to the **FC-USB** if the **OSD/PDB** is powered by the battery. 

From what I've got reading the documentation, this erratic behaviour is probably due to the fact that the **SPF3 UART1** is shared between the **OSD/PDB** headers and the USB Silabs chip... However, since there is a **bus switch** on the **OSD/PDB**, I wonder whether there is something I'm missing... Is it possible to connect to the flight controller USB while the two boards are stacked together and connected to the battery? What is exactly the purpose of this switch? 

![detail-busswitch-02](https://cloud.githubusercontent.com/assets/1591429/25131231/40929d88-2445-11e7-9a19-e07078817f35.jpg)

**Comment by hydra** [comment]
The behavior is not erratic, it's consistent when 2 devices try and use the same serial signals.

the SPRACINGF3 cannot be powered at the same time as the SPRACINGF3OSD/PDB unless the bus switch is disabled on the SPRACINGF3.

There is currently no software support for the bus switch other than to enable it at boot on the OSD/PDB board.

At one point it was envisaged that there might be a need to disable the bus switch. There are some flashing scenarios where the bus switch helps too.

The SPRACINGF3EVO and SPRACINGF4EVO don't use the CP2102 that the SPRACINGF3 has and thus do not have the issue.

There's no way the SPRACINGF3 can detect USB connection, so no way to disable to bus switch.
It's technically possible to detect USB connection on the OSD to disable the bus switch but nothing like that has been implemented.

Perhaps it's possible to disable the bus switch via some GUI control so that the FC can be configured.

This only affects the SPRACINGF3.  SPRACINGF3EVO, SPRACINGF4EVO are unaffected.  SPRACINGF3 has been discontinued for over a year now.

If you have any ideas please let me know, perhaps we could add something that might help but I can't think what/how at this time.

**Comment by biank88** [comment]
Thanks! I think you should mention this problem in the docs for the SPF3-OSD/PDB.
In my case, in order to maintain the possibility to program the FC, I've desoldered the uart headers and I've rewired the OSD/PDB-UART1 to SPF3-FC-UART2.
