### ISSUE TITLE
naze firmware 2.1.0, no access to variable mag_hardware

### ISSUE THREAD

**Issue by matzeking1** [cleanflight/cleanflight#3011]
# A - Description

-- there's no access to variable mag_hardware
-- "get mag" or "get mag_hardware" always results in "Invalid name"
-- maybe they don't exist?

-- always on Firmware 2.1.0 for naze. 
-- Firmware 2.0.5 works like it should (on my mind)

-- I can't find notes that there changed something

# B - Steps To Repeat

-- always on Firmware 2.1.0 for naze

# E - Version Information

Configurator: v2.1.0

# E - Other information

-- naze 32 full version

**Comment by McGiverGim** [comment]
If I'm not wrong, the MAG driver has been removed from the NAZE firmware because it has not enough space for it in the latest versions. If you need it, you must compile a version removing things not needed (protocols of RX and telemetry not used, by example) and adding the MAG.
You can find some info here: https://github.com/cleanflight/cleanflight/blob/master/docs/Customized%20Version.md
