### ISSUE TITLE
GUI firmware backwards compatibility

### ISSUE THREAD

**Issue by dogz85** [cleanflight/cleanflight#382]
recently i have had to update firmware (and reset all the settings on the board)because i needed to change something on the board. 

Because the the chrome app updated automatically i couldn't talk to the board (naze32) anymore. 

please add a way for the current GUI to talk to older firmwares so that one does not need to constantly update firmwares or use dodgy workarounds.

**Comment by vadav** [comment]
Connecting a board with old fw gave me this..    CLI access and some info

![updatemsg](https://cloud.githubusercontent.com/assets/9387279/5801331/12bc47a6-9fea-11e4-80df-8b06ac2f9a41.jpg)

**Comment by hydra** [comment]
please search for other issues before creating new issues.

https://github.com/cleanflight/cleanflight-configurator/issues/40
https://github.com/cleanflight/cleanflight-configurator/issues/41
https://github.com/cleanflight/cleanflight-configurator/issues/37
https://github.com/cleanflight/cleanflight-configurator/issues/29

The issue is with the configurator, not the firmware, this is posted in the wrong place.

There is now some backwards compatibility code in the latest configurator.

We know this is an issue users are having and we will continue to improve things.
