### ISSUE TITLE
Comms - Mag indication not displayed on OSD

### ISSUE THREAD

**Issue by steveomg** [cleanflight/cleanflight#49]
Mag "M" is not highlighted when enabling or disabling mag while running KVOSD latest.  This works in baseflight.

**Comment by hydra** [comment]
In MWOSD there is this:

https://code.google.com/p/multiwii-osd/source/browse/MW_OSD/Config.h#35

```
//#define BASEFLIGHT                // Undefine this if you are using BASEFLIGHT / NAZE32 to correct for heading dispaly issues
```

Since KVOSD is discontinue and this setting exists perhaps the only issue is one of documentation?

Can someone document the process of setting up MWOSD to work with cleanflight and submit as a pull-request?
