### ISSUE TITLE
FrSky RX Serial data

### ISSUE THREAD

**Issue by grayver** [cleanflight/cleanflight#495]
Is there a way to read FrSky receiver serial data? For example, I want to read RSSI from FrSky D4R-II via UART2.

**Comment by hydra** [comment]
This isn't really the place to ask questions like this.  Please use the forums and irc. 

Since i have a spare minute i will answer and give you a suggestion:  The RX does not send data to the FC.  Instead however you can feed the rssi output from the RX into the FC via the RSSI ADC feature and then use MSP to get the ADC value.

Closing this issue. Hope this helps.
