### ISSUE TITLE
enhancements.... thoughts on these

### ISSUE THREAD

**Issue by handsomejackuk** [cleanflight/cleanflight#634]
Have  a very active mind and always thinking of enhancements, just wish i was better at programming as i would love to have a go my self....

anyway... using barometer  would there be a way of using a rate of climb or rate of descent with the barometer switched on, was out with my brother in law the other day and his phantom has a similar feature so that if baro / alttitude hold is on and the throttle is lowered the quad will descend at that rate. until maybe a set height ?

leds simple configuration not led strips ws2812b just standard leds available on an output, i have a similar setup on my multiwii version 2.3 with landing lights  led max, strobes,  i realise that a transistor will have to be used to provide the current on the naze outputs...

and another thought....(not clenflight). When using the altitude hold i have only used it a few times. and seem to remember that the throttle has to be at mid..1500 is there anyway to be able to confirm this.... ... maybe a beep at 1400-1600   i think this would have to be at the transmitter, i note that open tx has centre beep on the pots on a turnigy 9xr....

also i have requested ez gui to have the current meter implemented on the dashboard..

thanks for version 1.8 looking forward to testing it soon keep up the brilliant work on this firmware...

**Comment by hydra** [comment]
Please open one issue per feature request, describe them fully with expected behaviour if possible please.  It's impossible to use the issue tracker when there's more than one issue/feature per ticket.

I dont think there's any interest in using normal LEDs especially since the wiring overhead and pin allocation is further complicated.

For support (reference usage of alt-hold) please use IRC or the forums.
