### ISSUE TITLE
Option RX_SERIAL not saves via GUI

### ISSUE THREAD

**Issue by azaitsev** [cleanflight/cleanflight#731]
After reboot no receiver mode selected

**Comment by thenickdude** [comment]
Try configuring the port on the ports tab for Rx serial before enabling the feature.

**Comment by azaitsev** [comment]
It helps. But it's not user-friendly.
Also no power on my RX via SBUS.

**Comment by azaitsev** [comment]
My bad. Forgot to connect battery :)

**Comment by NullVoxPopuli** [comment]
I second this. 
Configuring RX_SERIAL is not as intuitive as it should be.

I have a suggestion, which I'll post to the configuration issues: 
It should be possible to select "popular" receivers, and have the configurator set whatever parameters it needs to, so that there is less command line / apparent not saving due to feature conflicts.

**Comment by hydra** [comment]
This is a configurator issue. closing. please open in the configurator tracker.

**Comment by Propitiation** [comment]
where is the configurator tracker?

**Comment by thenickdude** [comment]
https://github.com/cleanflight/cleanflight-configurator/issues
