### ISSUE TITLE
Sensors - Improve current averaging code so that negative values are never produced.

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#88]
during early startup it has been observed that the mAhDrawn value is negative.  This has a knock-on effect with the msp and telemetry code that require the value to be constrained by via constrain() calls during serialization.

during serialization the numbers should only need to be constrained to the maximum value for serialiation, but because of the issue the have to be constrained to the minimum value too.
- fix the averaging code so it does not produce negative values
- use max(value, 0xffff) instead of constrain(value, 0, 0xffff) to reduce code size.

**Comment by ProDrone** [comment]
Looking for the root cause of this problem, i found this:
* __Why__ is this a signed value, should it not be always positive?: https://github.com/cleanflight/cleanflight/blob/master/src/main/io/serial_cli.c#L365
* These variables are signed and thus allowed to represent negative value: https://github.com/cleanflight/cleanflight/blob/master/src/main/sensors/battery.c#L118-L119
* Here: https://github.com/cleanflight/cleanflight/blob/master/src/main/sensors/battery.c#L111 it looks like we subtract a non-negative value `batteryConfig->currentMeterOffset` from __signed__ `milivolts`, if `milivolts` is lower then `batteryConfig->currentMeterOffset` it will become __negative__.

I do not have a current sensor installed, so after possible modification i cannot test this.

**Comment by thenickdude** [comment]
Negative current sensor readings have a legitimate physical meaning because regenerative braking can cause battery charging in flight.

**Comment by ProDrone** [comment]
@thenickdude True, but the amount of energy is *very* little. Most of the energy is locally exchanged between the poles/motors (and hence not withdrawn from the battery). The problem with regenerative braking is one of voltage. If you don't give it a return path to the battery, that voltage will rise as can be observed when hooked up to a bench power supply.

Since this issue is about never producing negative values, i thought it best to keep negative values out to avoid these registration problems. However if you think otherwise it would be interesting to have a blackbox log of returned battery charge.

**Comment by thenickdude** [comment]
Why ignore negative values when the sensors can produce them?

**Comment by ProDrone** [comment]
@thenickdude Wel, I __agree__ with you. It is just that this issue is about preventing negative value :grin:
