### ISSUE TITLE
Flight - Investigate mixer motor minimum

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#897]
@Crashpilot1000 said this, in the Yaw bounce-back issue, it is worthy of investigation.

https://github.com/cleanflight/cleanflight/issues/741#issuecomment-95542363

this part(original CF/MWII/BF) still gives me shivers: https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/mixer.c#L691 because the overshoot or "maxMotor" is not limited by the actual pwm range - so in high throttle situations (even on a single motor, or 2 motors during yaw) it can press down the whole motoroutput to minthrottle (ensured by constrain further down the road) anihilating any regulation and yaw. 

From my testing I don't see such disasters (unless you crank up the P's to unhealthy values) BUT I def. see a loss / degradation of yaw control in such situations (because yaw is very sensitive). 

From my testing it is better to ensure a minimal-left-over throttle of 15% of the physical esc pwm range. 

So capping "maxMotor" to being maximal maxthrottle + (maxthrottle-minthrottle) \* 0,85 is my proposal. (Note: the actual code will be a little different)

Edit: Do the 85%limit on motor[i] so "maxMotor" is limited as well. (something like this: https://github.com/Crashpilot1000/TestCode3/blob/master/src/mixer.c#L408)
Cheers Rob

**Comment by thenickdude** [comment]
Not sure about this one. The current code allows attitude to be pretty much maintained when one motor fails (because the control signal to that failed motor becomes high enough to force all the others to zero, preventing the craft from flipping itself over). This has allowed me flat landings on several occasions that I don't think would be possible with that suggestion.

However, I think there could be an improvement possible in conflict resolution when different control goals collide (pitch/roll/yaw/throttle).
